# Generated by Django 4.2.5 on 2023-09-23 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthGuide', '0002_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=255)),
                ('ghCardNumber', models.CharField(max_length=255)),
                ('patientID', models.CharField(editable=False, max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=15)),
                ('guardianContact', models.CharField(max_length=15)),
                ('patientImg', models.ImageField(blank=True, null=True, upload_to='patient_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
